- themes/light.json
This fixes the `invalid.illegal` scope. For some reason the red background is not shown, making the white text unreadable.
Before | After
--- | ---
---
Fixes https://github.com/primer/github-vscode-theme/issues/1
> Fix invalid scope

- themes/light.json
Fixes #5 
I updated the theme to use the same status bar colors when in opening a new window/no workspace:
Also updated the status bar colors for when you are debugging, since there were none defined:
> Add status bar colors

- src/theme.js
- themes/dark.json
This makes the `list.activeSelection` a bit lighter:
Before | After
--- | ---
It should fix #11
> Custom list.activeSelection

- src/theme.js
- themes/dark.json
- themes/light.json
I decreased the whitespace characters contrast. They were bit too visible for users who render them. Used colors from the Primer's color system.
**Screenshots of the new colors:**
> Decrease whitespace characters color contrast

- src/theme.js
- themes/dark.json
- themes/light.json
This enables [semantic highlighting](https://code.visualstudio.com/docs/getstarted/themes#_semantic-highlighting). I haven't looked into the details, but I can see a difference with this [sample TS code](https://github.com/atom/language-examples/blob/b0aa83840d93ca10ab093e121bcfdfa1e5b54163/languages/typescript.ts#L17-L26):
Before | After
--- | ---
I guess semantically it's not a `variable` but a `property` that falls back to the `variable.other` color? 🤔 Anyways, we can make further tweaks if needed.
---
Closes https://github.com/primer/github-vscode-theme/issues/25
> Enable semantic highlighting

- src/theme.js
- themes/dark.json
This is a "quick fix" https://github.com/primer/github-vscode-theme/issues/19 and makes strings a bit darker:
Before | After
--- | ---
> Darker strings

- src/theme.js
- themes/dark.json
The dark theme debug foreground color is dark text on a dark background, which makes it hard to read. This updates the foreground color to be white.
<hr>
Closes #34
> Update debug foreground color for dark theme

- src/theme.js
- themes/dark.json
This fixes the invisible hovered command palette item for the dark theme.
---
Closes #14
> Increase contrast for list.hoverBackground

- src/theme.js
I think we may also want to use softer and less contrasting colors for the light theme.
In dark theme the markup.list looks like white, so I changed the yellow[9] for markup.list to be black in light theme.
---
Closes https://github.com/primer/github-vscode-theme/issues/50
> Soften foreground color for dark theme fixes #50

- src/theme.js
This should make future changes easier to different people especially if we consider adding a high contrast version of the theme.
> Quick improvements to #65

- src/theme.js
This adds support for `statusBarItem.prominentBackground`.
```json
"statusBarItem.prominentBackground": pick({ light: "#e8eaed", dark: "#282e34" }),
```
---
- Superseeds and closes #77
- /cc @phgmacedo
> Add statusbar prominent background

- src/theme.js
This improves syntax highlighting for JavaScript/React.
Before | After | github.com
--- | --- | ---
> Improve JavaScript/React highlighting

- src/theme.js
This fixes a few issues that got reported after publishing the new dark theme:
Before | After
--- | ---
Closes #106
Before | After
--- | ---
Closes #109
Closes #107
Before | After
--- | ---
Closes #115
> Fix various issues for the new dark theme

- src/theme.js
This PR changes the `editorForeground` color of VSCode to use Primer's primary text color value. This removes the hardcoded value we have set for the dark dimmed theme.
> Use primer's primary text color for editor foreground

- src/theme.js
This PR implements the use of primer's 'underlinenav.borderActive' color for VSCode's activity bar, tab and panel borders. Currently, all GitHub theme's have a fixed color value of `#f9826c` for these elements, this PR change would apply the correct primer color for all themes.
- GitHub Light Default: `#f78166`
- GitHub Dark Default: `#f9826c`
- GitHub Dark Dimmed: `#f78166`
> Use primer's official colors for activity bar, tab & panel borders

- src/theme.js
Fixes https://github.com/primer/github-vscode-theme/issues/152.
The diff colors needs alpha to make the selection visible.
> Fix diffs (Light Default)

- src/classic/theme.js
- src/theme.js
This closes https://github.com/primer/github-vscode-theme/issues/141.
It colors `editor.linkedEditingBackground` and overrides the default red background:
Before | After
--- | ---
It's the same color as `editor.inactiveSelectionBackground`. Also, in my case, I think the border comes from `wordHighlight`.
> Style linkedEditing

- src/classic/theme.js
- src/theme.js
This uses opacity for the `editor.foldBackground` so that selections on folded lines are still visible.
Fixes https://github.com/primer/github-vscode-theme/issues/43
Fixes https://github.com/primer/github-vscode-theme/issues/53
> Use opacity for foldBackground

- package-lock.json
- package.json
This bumps `@primer/primitives` to `4.2.2`. It includes https://github.com/primer/primitives/pull/73 and should fix the low contrast of the terminal colors in `GitHub Light Default`: 
Before | After
--- | ---
Fixes https://github.com/primer/github-vscode-theme/issues/157
Fixes https://github.com/primer/github-vscode-theme/issues/155
> Fix terminal colors (GitHub Light Default)

- src/theme.js
This PR fixes the sidebar contrast between active and inactive list items. See screenshots below of before and after:
| GitHub Light Default | GitHub Dark Default | GitHub Dark Dimmed |
| --------------------------- | --------------------------- | ---------------------------- |
| ![light-old](https://user-images.githubusercontent.com/28626241/115106582-88c02200-9f5d-11eb-99ed-8e8d26bdd970.png) | ![dark-old](https://user-images.githubusercontent.com/28626241/115106589-95dd1100-9f5d-11eb-9f62-97d5c059eec1.png) | ![dimmed-old](https://user-images.githubusercontent.com/28626241/115106597-9e354c00-9f5d-11eb-955b-1c1bf1fba59e.png) |
| GitHub Light Default | GitHub Dark Default | GitHub Dark Dimmed |
| --------------------------- | --------------------------- | ---------------------------- |
| …
> Fix sidebar contrast

- src/classic/theme.js
- src/theme.js
So other decorations (like selections) are still visible underneath.
Fixes https://github.com/primer/github-vscode-theme/issues/136.
> Use opacity for stackFrameHighlight

- package-lock.json
- package.json
This bumps `@primer/primitives` to `4.3.0`. It includes the changes of https://github.com/primer/primitives/pull/78.
Before | After
--- | ---
> Improve ANSI colors

- src/theme.js
The `border.overlay` will be removed from https://github.com/primer/primitives/pull/82. In preparation for that change, this PR replaces `border.overlay` with `border.primary`. There should be no visual change since both variables use the same color.
> Replace border.overlay with border.primary

- src/classic/theme.js
- src/theme.js
This PR fixes #166 and adds styles for the secondary button style. Tried my best to map to the existing colors but VS Code does not have button border colors so tried to use `activeBg` for the buttons and `hoverBg` for the hover. Happy to adjust the PR for alternate colors.
> Add support for secondary button style

- src/classic/theme.js
> Set terminal.tab.activeBorder based on editor tab

- .changeset/fast-adults-clean.md
- src/theme.js
This fixes https://github.com/primer/github-vscode-theme/issues/255.
Seems we forgot to rename `dimmed` to `dark_dimmed` in the theme file.
> Fix Dark Dimmed

- .changeset/rare-games-sneeze.md
- src/classic/theme.js
- src/theme.js
It is very useful in Semantic highlighting.
> feat: add underline support

- .changeset/mean-geckos-shout.md
- src/classic/theme.js
- src/theme.js
This updates the `statusBarItem.remoteForeground/Background` to match the rest of the status bar:
Before | After
--- | ---
It's a combination of
> Update remote statusbar item

- .changeset/dirty-rivers-clap.md
- src/theme.js
This fixes https://github.com/primer/github-vscode-theme/issues/264 by improving contrast for some icons:
Before | After
--- | ---
> Fix icons in high contrast themes

- .changeset/blue-ads-notice.md
- src/theme.js
This improves the diff colors by making changed text stand out against the background. E.g. `3` changed to `8`:
Before | After
--- | ---
Also the diff colors are now semi-transparent so that selection can be seen:
Before | After
--- | ---
> Improve diff colors

- .changeset/happy-cougars-promise.md
- src/theme.js
This PR adds styles to color inlay hints. I based the style off how `inline code` looks on GitHub, using the appropriate primer colors.
Both examples are of Rust code using the Light Default & Dark Default themes. The example code is taken from Rust By Example.
**Light Default**:
**Dark Default**:
> Add inlay hint colors

- .changeset/late-chairs-impress.md
- src/theme.js
This closes https://github.com/primer/github-vscode-theme/issues/282 by increasing the foreground color of the terminal. It's more noticeable for dark themes.
Before | After
--- | ---
> Increase contrast of the terminal

- .changeset/eleven-jobs-tickle.md
- src/theme.js
This PR adds bracket pair colorization matching the active theme. The changes essentially bring to the new themes a feature already present in the [legacy](https://github.com/primer/github-vscode-theme/blob/649311a727bd8022dd8125f4de1bbdc042950d10/src/classic/theme.js#L216) ones.
Here is a screenshot of what it looks like:
> Add bracket pair colorization to new themes

- .changeset/lemon-jokes-retire.md
- src/classic/theme.js
This closes https://github.com/primer/github-vscode-theme/issues/276 by making the same changes as in https://github.com/primer/github-vscode-theme/pull/193 also to the classic `GitHub Light` + `GitHub Dark` themes.
Before | After
--- | ---
> Colorize inline code blocks for the classic themes

- .changeset/rare-terms-knock.md
- src/theme.js
This closes https://github.com/primer/github-vscode-theme/issues/271 by making sure the background in High Contrast themes has enough contrast.
Before | After
--- | ---
> Improve selection in High Contrast themes

- .changeset/eight-onions-grow.md
- src/classic/theme.js
- src/theme.js
This closes https://github.com/primer/github-vscode-theme/issues/260 by adding support for ~~strikethrough~~.
Before | After
--- | ---
> Add support for strikethrough

- .changeset/curvy-falcons-invent.md
- src/classic/theme.js
- src/theme.js
This fixes https://github.com/primer/github-vscode-theme/issues/251 by removing the `string source` scope override.
Not sure why it initially was added, but it should colorize things like inline CSS in HTML.
Before | After
--- | ---
> Remove `string source` scope

- .changeset/unlucky-lamps-brush.md
- src/theme.js
This closes https://github.com/primer/github-vscode-theme/issues/249 by reducing the contrast of line numbers. It's currently hard to see which line is the active one (`53` in the example below).
Before | After
--- | ---
> Reduce contrast of line numbers

- .changeset/curvy-falcons-compare.md
- src/theme.js
This closes https://github.com/primer/github-vscode-theme/issues/245 by using `color.danger.fg`. It should have the effect that it's red in all themes, except for the color blind themes where it's "orange":
Colorblind themes | Other themes
--- | ---
Orange | Red
> Improve breakpoint icon for colorblind themes

- .changeset/tall-suits-knock.md
- src/theme.js
This closes https://github.com/primer/github-vscode-theme/issues/242 by reducing the contrast for whitespace characters.
Before | After
--- | ---
> Reduce contrast for whitespace characters

- .changeset/quiet-rules-rest.md
- src/theme.js
This changes the property-name in JSON files to `green` and should make it easier to see the "value":
Before | After
--- | ---
- closes #20
- closes #69
We have been holding off with this change mainly to stay close to github.com, but it now seems things changed and the property names in JSON files are now green. E.g. https://github.com/primer/github-vscode-theme/blob/main/package.json So it makes sense this theme follows up with the same change.
> Colorize JSON property-name

- .changeset/grumpy-panthers-remember.md
- src/theme.js
This closes https://github.com/primer/github-vscode-theme/issues/133.
`punctuation.definition.string` should not be needed since it just inherits the color from `string` anyways.
> Remove `punctuation.definition.string`

- .changeset/itchy-spies-jog.md
- src/theme.js
This closes https://github.com/primer/github-vscode-theme/issues/135 by making the `editorIndentGuide` semi-transparent. Now it doesn't cover selections anymore.
Before | After
--- | ---
> Make `editorIndentGuide` semi-transparent

- .changeset/great-chairs-knock.md
- src/theme.js
This helps close #326. The change affects go (golang), python, and possibly others. The changes will make variables inside of strings (placeholders) more visible. Below is a demo of that.
> Add better placeholder colors for semantic highlighting

- .changeset/good-books-care.md
- src/theme.js
> [FIX] Update diff highlighting

- .changeset/calm-clocks-hunt.md
- package.json
This fixes https://github.com/primer/github-vscode-theme/issues/321 by switching `uiTheme` to `hc-light` for the `GitHub Light High Contrast` theme. 
Before | After
--- | ---
> Fix tab fg color for `GitHub Light High Contrast`

- .changeset/light-bottles-taste.md
- package.json
- yarn.lock
This bumps `primer/primitives` to `7.10.0`.
There are quite a bit of changes, see under [Colors changed](https://github.com/primer/github-vscode-theme/pull/344#issuecomment-1370574837). But it should bring this theme in sync with github.com and should fix https://github.com/primer/github-vscode-theme/issues/290.
`7.1.1` | `7.10.0`
--- | ---
```
yarn add @primer/primitives@7.10.0
```
> Bump `primer/primitives` to `7.10.0`

- .changeset/great-socks-type.md
- src/theme.js
This improves the slider contrast for the minimap. It also keeps it in sync with the editor scrollbars.
Closes https://github.com/primer/github-vscode-theme/issues/200
Before | After
--- | ---
Take a look at the [Contribute](https://github.com/primer/github-vscode-theme#contribute) section for more information on how test your changes locally.
> Improve minimap slider contrast

- .changeset/silver-fans-promise.md
- src/theme.js
This removes the `underline` for the text part of links in markdown. 
```diff
[link](https://github.com)
-  ----  ------------------
[link](https://github.com)
+        ------------------
```
Doing so allows the link text to be _italic_ when the whole text block is italic. I think this is also better because only the URL part is actually clickable and should be underlined.
Closes https://github.com/primer/github-vscode-theme/issues/74
Before | After
--- | ---
Take a look at the [Contribute](https://github.com/primer/github-vscode-theme#contribute) section for more information on how test your changes locally.
> Remove underline from link text

- .changeset/itchy-crabs-reply.md
- src/theme.js
Updating the `settings.headerForeground` from `fg.muted` to `fg.default` to make it more distinguishable from the rest of the options.
Closes #199 
- [] Added/updated documentation/README
Take a look at the [Contribute](https://github.com/primer/github-vscode-theme#contribute) section for more information on how test your changes locally.
> Update the color for the active header foreground 
